### ISSUE TITLE
Wrong date picked

### ISSUE THREAD

**Issue by PatMei** [KoljaWindeler/ics#3] opened 2020-03-23 11:48 UTC
Hello Kolja,

I use the following trashcalendar:
https://awido.cubefour.de/Customer/awb-duerkheim/KalenderICS.aspx?oid=00000000-0000-0000-0001-000000000706&jahr=2020

It shows me a date (example startswith: Papier) in few month (Monday, 13.07.2020 (113)) but next time for paper will be in a week. Hope you can reproduce the error ;)

Cheers,
PatMei

**Comment by KoljaWindeler** [comment] 2020-03-23 11:53
hi, yes I can reproduce the error ... the reason is the very strange format of that ICS file. The events are completely out of order. I'll have a look how to fix it. Might take some time.
Kolja

**Comment by KoljaWindeler** [comment] 2020-03-23 12:51
Hi again, I've fixed the sorting in commit https://github.com/KoljaWindeler/ics/commit/52a2add16ef8c3ed642b7e6932757d1b88eaaa5a
could you have a look?
Thanks Kolja

**Comment by PatMei** [comment] 2020-03-23 14:07
Looks good 👍  Thank you for your work!
Can you also change the calculation? It is still one day leftfor picking up trash, but today is the day. Setting it to "0" or "Today".

![Unbenannt](https://user-images.githubusercontent.com/59027829/77324886-b82f3b80-6d17-11ea-84a2-471a616349ac.JPG)

**Comment by KoljaWindeler** [comment] 2020-03-23 15:39
Ha, tricky. That was sadly a bug introduced by the date handling.
Thats fixed now. I hope that all of you see this before adding complex logic that relies on the state. 
Thanks for mentioning it.

**Closed** 2020-03-23 18:30 UTC

**Comment by PatMei** [comment] 2020-03-23 19:47
So far, it is working :) thank you very much for caring about!

Cheers,
PatMei
